### ISSUE TITLE
End to end test #1: Streaming from a WISH event file to a consumer

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#1]
Not too dissimilar to the existing Kafka example, but using a real events file and travelling across the "kafka cluster" to a simple client.

**Comment by matthew-d-jones** [comment]
See https://github.com/ScreamingUdder/isis_nexus_streamer

Still to do:
- end to end system tests
- performance tests
- see what performance is like serving data from memory, or uncompressed file? (currently heavily limited by decompressing the NeXus file)

**Comment by mattclarke** [comment]
I am going to break these out in separate issues
