### ISSUE TITLE
Set up a Jenkins build server

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#12]
Once we have a repo we should set up an automated build.

**Comment by matthew-d-jones** [comment]
We currently have CI via Travis: https://travis-ci.org/ScreamingUdder/isis_nexus_streamer
Afonso is looking into setting up CI with Jenkins (v2) in Denmark, we can request login access to the virtual machine.

**Comment by mattclarke** [comment]
Start by getting the epics forwarder building in there.

**Comment by matthew-d-jones** [comment]
DMSC will also run Windows Jenkins build servers. Should we close this ticket?
