### ISSUE TITLE
End to end system tests

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#14]

**Comment by matthew-d-jones** [comment]
In progress.
Plan is to use a python script and call the executables via the subprocess library. This how system tests are implemented for the Google Tests project:
https://github.com/google/googletest/blob/master/googletest/test/gtest_test_utils.py

**Comment by matthew-d-jones** [comment]
End-to-end test implemented, process from launching the producer to the consumer having received all events from the file is timed. It is checked that a message is received for every frame.
Next I will try to wrap JMXterm with python and use it to collect information about average data transfer rates from the broker.

**Comment by matthew-d-jones** [comment]
Done, ISIS nexus streamer demonstrates system tests, including collecting metrics from broker.
