### ISSUE TITLE
Performance tests for non-compressed data

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#16]
See what performance is like serving data from memory, or uncompressed file? (currently heavily limited by decompressing the NeXus file)

**Comment by matthew-d-jones** [comment]
In progress. I've created a python script to convert a compressed Nexus file to an uncompressed one:
https://github.com/ScreamingUdder/isis_nexus_streamer/blob/master/data/convert_hdf5_file_to_uncompressed.py

**Comment by matthew-d-jones** [comment]
Testing end-to-end with the producer and consumer on my machine and using the physical machines as the cluster shows throughput limited by the network. It reaches a steady state of 500 Mbps up and 500 Mbps down.

However when running only the producer it reaches only 700 Mbps up. This is using ~10MB message size which is reported to be bad for performance so will also try different message sizes: https://github.com/ScreamingUdder/isis_issues/issues/18

**Comment by matthew-d-jones** [comment]
Confirmed broker cpu limited (at least when using ~10 MB message size). Publishing to a topic with two partitions, and thus sharing the load across two broker machines, resulted in network limited throughput again (1 Gbps upload when running just the producer).
