### ISSUE TITLE
Logs via Kafka and Elasticsearch

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#24]
At some point one of the in-kind projects will be interested in this, so we should be prepared

**Comment by matthew-d-jones** [comment]
CERN use Logstash-Elasticsearch-Kibana: https://medium.com/@ghoranyi/needle-in-a-haystack-873c97a99983#.g2ykdk18r

**Comment by matthew-d-jones** [comment]
Logstash has plugins for Kafka and JMX, so the Elastic stack could be used for real-time log visualisation and streaming system monitoring.
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jmx.html
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html

Alternatively there is a Kafka Connect module for Elasticsearch. Is this bidirectional, or just a kafka->elastic?

**Comment by matthew-d-jones** [comment]
To feed Kafka metrics into ELK there is an Elastic Beat https://github.com/gingerwizard/kafkabeat

**Comment by matthew-d-jones** [comment]
The Kafka connect module to feed data into Elasticsearch works well. I'm not so impressed with Kibana, does not seem very stable.
Check out Grafana https://www.youtube.com/watch?v=d6KicssNzxM
In particular templating functionality looks very useful for automatically creating plots from different sample log sources in a single Kafka topic.

Write up findings on the ESS wiki.

**Comment by matthew-d-jones** [comment]
Check that using Graylog and the Kafka Connect Elasticsearch module also works.

**Comment by matthew-d-jones** [comment]
Findings written up on the wiki:
https://ess-ics.atlassian.net/wiki/display/DMSC/Interfacing+Log+Visualisation+and+Kafka
