### ISSUE TITLE
Performance test for EPICS forwarder

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#28]
Set up a large number of PVs and IOCs and see how the performance looks.

Things to try:
- How does it handle a 100 PVs updating at a second?
- How about a thousand PVs?
- What does it do for disconnected PVs?
- Does it batch up values or are they sent to Kafka individually?

Does it make sense to try to batch slow sample environment? For example: a batch of a second's activity?

**Comment by matthew-d-jones** [comment]
Duplicated in #65
