### ISSUE TITLE
Simulate sample environment

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#37]
Take some of the IBEX IOCs and set them up with LeWIS.

Some ideas for IOCs to write simulators for:

- Eurotherm (might be complex)
- Julabo
- Kepco
-

**Comment by matthew-d-jones** [comment]
We currently only have the containerised ESS chopper simulation for this. It would be useful to have others. There is at least one Windows path hard-coded in the IBEX simulations currently, but this should be solvable. Perhaps containerising more IOCs and testing with the forwarder would be a suitable task for a work experience placement lead by Jack?

**Comment by matthew-d-jones** [comment]
The Forwarder now has a random number update generator and Jack has implemented system tests for a wide range of types using EPICS soft ioc.
