### ISSUE TITLE
Set up an event streaming service for LARMOR

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#38]
Let's push on with getting something working for ISIS.
We can use the new cluster if we get one, otherwise the test cluster can be used.
It will need to be made clear to the scientists that this is a test system and may disappear at any time.

Needs the modified version of MANTID.

This will help us towards our goal of having a full prototype for June 2018.

**Comment by matthew-d-jones** [comment]
Done
