### ISSUE TITLE
Un-aggregate the ICP data stream

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#40]
Freddie's ICP program acts as an aggregator - it may be useful for us to un-aggregate it to better match what the ESS may do stream wise.
It will allow us to change the stream formats, topics etc. to try things out on a real instrument without Freddie having to modify the ICP.

**Comment by matthew-d-jones** [comment]
First step is putting sample environment data into a separate topic, underway.

**Comment by matthew-d-jones** [comment]
Sample environment measurements are now forwarded directly from EPICS to Kafka instead of via the ICP, configuration of the forwarder is handled by a python service which talks with the block server: https://github.com/ScreamingUdder/isis_issues/issues/62
