### ISSUE TITLE
Apache Streams: event summing

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#41]
On SANS2D and LOQ they have an extra card in their DAE to sum the data counts per pixel so they can be plotted in a simple detector view.
LARMOR and ZOOM may not have these cards, so is it possible to use Streams to replicate this behavior in software?

How easy is it to write a Stream?
How much CPU/RAM does it take when running?

**Comment by matthew-d-jones** [comment]
@mattclarke Potential apprentice task?

**Comment by matthew-d-jones** [comment]
See https://github.com/ScreamingUdder/detection-count-stream-processor
