### ISSUE TITLE
Using Docker rather than Vagrant

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#48]
Needs more thinking about.

**Comment by matthew-d-jones** [comment]
https://jeqo.github.io/post/2017-01-15-scale-kafka-containers/

**Comment by matthew-d-jones** [comment]
This is started here: https://github.com/ScreamingUdder/docker-compose-full-system
but there are more components to containerise.

**Comment by matthew-d-jones** [comment]
In progress, Jack is writing system tests using docker.

**Comment by matthew-d-jones** [comment]
See https://github.com/ess-dmsc/forward-epics-to-kafka/pull/67
