### ISSUE TITLE
End-to-end tests for the EPICS forwarder

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#50]

**Comment by matthew-d-jones** [comment]
We will try containerised, simulated IOCs with the forwarder, see https://github.com/ScreamingUdder/docker-compose-full-system
Configuration messages can be written in json files and sent to the forwarder using Kafkacat. The process should be made as simple as possible and be documented, for example see https://github.com/ess-dmsc/kafka-to-nexus/blob/master/manual-testing/manual-testing.md

**Comment by matthew-d-jones** [comment]
https://github.com/ess-dmsc/forward-epics-to-kafka/pull/67
