### ISSUE TITLE
Kafka Manager for Kafka 10.X

### ISSUE THREAD

**Issue by matthew-d-jones** [ScreamingUdder/isis_issues#56]
Yahoo's Kafka Manager was a very useful tool, particularly for browsing, configuring and deleting topics. Unfortunately it does not support Kafka 10.X onwards.
https://github.com/yahoo/kafka-manager

Add recent version support to Kafka Manager, or implementing our own web UI.

**Comment by mattclarke** [comment]
This will be implemented in Python using Flask or Java using Play.

**Comment by matthew-d-jones** [comment]
Kafka-Manager was updated and is compatible with the latest version (0.10.2.0).
