### ISSUE TITLE
[DM-79] Look into Kafka system diagnostics/monitoring

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#7]
https://ess-ics.atlassian.net/browse/DM-79

**Comment by matthew-d-jones** [comment]
I have started adding some information on Kafka monitoring tools to the wiki: https://ess-ics.atlassian.net/wiki/display/DMSC/Kafka+Notes

**Comment by matthew-d-jones** [comment]
I have demonstrated wrapping jmxterm with python and using it to collect metrics from the broker during system tests: https://github.com/ScreamingUdder/isis_nexus_streamer/blob/master/system_tests/test_utils.py
